#Deployment
###controllers/pb-deploy.tml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employeeportal-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
  minReadySeconds: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: employeeportal-app
  template:
    metadata:
      labels:
        app: employeeportal-app
    spec:
      containers:
      - name: employeeportal-container
        # image: 268360024445.dkr.ecr.us-west-2.amazonaws.com/petclinic-application:latest-11
        image: kavyapallamreddy/employee-portal-application:2
        imagePullPolicy: Always
        resources:
          limits:
            cpu: '1'
            memory: '500Mi'
          requests:
            cpu: '1'
            memory: '500Mi'
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: regcred



