# Service - LoadBalancer
# # pb-service -lb.yml
apiVersion: v1
kind: Service
metadata:
  name: employeeportal-service
  labels:
    app: employeeportal-app
spec:
  selector:
    app: employeeportal-app
  type: NodePort
  ports:
  - nodePort: 31280
    port: 5000
    targetPort: 5000
