# Service - LoadBalancer
# # pb-service -lb.yml
apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
  labels:
    app: petclinic-app
spec:
  selector:
    app: petclinic-app
  type: LoadBalancer
  ports:
  - nodePort: 31280
    port: 5000
    targetPort: 5000
